### ISSUE TITLE
Docs: 요구사항 명세서 발표

### ISSUE THREAD

**Issue by fkdl0048** [fkdl0048/23_1_Capstone#1]
### 기한

2023/03/30 오후 2시 전까지 메일로 제출

### TODO

- [x] 프로젝트 이름
- [x] 프로젝트 개요(문제 설명서)
- [x] 유스케이스 다이어그램 설계
- [x] 클래스 다이어 그램
- [ ] 관계형 데이터 베이스
- [x] 시퀀스 다이어그램
- [x] 속성 정의
- [x] 오퍼레이션 정의
- [x] 관계 정보
- [x] 기타 요구사항

**Comment by fkdl0048** [comment]
프로젝트 명 R타운
